/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itl_energy.webapi;

import java.util.Set;
import javax.ws.rs.core.MediaType;

/**
 * Defines the REST application programmatically to avoid more config files.
 * 
 * @author Gordon
 */
@javax.ws.rs.ApplicationPath("api")
public class ItlEnergyApplication extends javax.ws.rs.core.Application {    
    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        // following code can be used to customize Jersey 2.0 JSON provider:
        try {
            Class jsonProvider = Class.forName("org.glassfish.jersey.jackson.JacksonFeature");
            // Class jsonProvider = Class.forName("org.glassfish.jersey.moxy.json.MoxyJsonFeature");
            // Class jsonProvider = Class.forName("org.glassfish.jersey.jettison.JettisonFeature");
            resources.add(jsonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(com.itl_energy.webapi.AuthenticationResource.class);
        resources.add(com.itl_energy.webapi.DeployedSensorResource.class);
        resources.add(com.itl_energy.webapi.HouseResource.class);
        resources.add(com.itl_energy.webapi.HubLogResource.class);
        resources.add(com.itl_energy.webapi.HubResource.class);
        resources.add(com.itl_energy.webapi.MeasurementResource.class);
        resources.add(com.itl_energy.webapi.ResourceBase.class);
        resources.add(com.itl_energy.webapi.SensorResource.class);
        resources.add(com.itl_energy.webapi.SiteResource.class);
        resources.add(com.itl_energy.webapi.StatusEventResource.class);
        resources.add(com.itl_energy.webapi.UserResource.class);
        resources.add(com.itl_energy.webapi.WeatherResource.class);
        resources.add(com.itl_energy.webcore.NotAuthorizedHandler.class);
    }
    
}
